name: execute python scripts in test on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t rsoccer:latest .

      - name: run all test scripts
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e PYTHONPATH=/workspace/src |
            -e WANDB_MODE=offline \
            rsoccer:latest \
            /bin/bash -c "for file in test/*.py; do echo 'executing $file...'; python \$file; done"
